# Generated by Django 3.1.2 on 2020-10-09 14:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quote',
            index=django.contrib.postgres.indexes.HashIndex(fields=['quote_type'], name='quotes_quot_quote_t_aa9a83_hash'),
        ),
    ]
